### ISSUE TITLE
npm start giving error 

### ISSUE THREAD

**Issue by manthanabc** [callbacc/Artistify#23]
heres the log 
```
9 verbose lifecycle music-app-server@0.2.0~start: CWD: C:\Users\manthan\repos\Artistify
10 silly lifecycle music-app-server@0.2.0~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle music-app-server@0.2.0~start: Returned: code: 1  signal: null
12 info lifecycle music-app-server@0.2.0~start: Failed to exec start script
13 verbose stack Error: music-app-server@0.2.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\manthan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\manthan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid music-app-server@0.2.0
15 verbose cwd C:\Users\manthan\repos\Artistify
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\manthan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error music-app-server@0.2.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the music-app-server@0.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Jardimjose** [comment]
Which npm start did you run? If you're working on the frontend make sure you cd frontend and then say npm start

**Comment by Jardimjose** [comment]
![image](https://user-images.githubusercontent.com/67740206/94987107-03969200-0564-11eb-81e4-3db32a0e10b5.png)

**Comment by manthanabc** [comment]
No I am trying to start the server

**Comment by IanWalston** [comment]
did you already run `npm i`?

**Comment by manthanabc** [comment]
yes i ran npm i

**Comment by Jardimjose** [comment]
what is your `NODE_ENV` set to?

**Comment by Jardimjose** [comment]
You can also try by clearing your cache and then updating npm

**Comment by callbacc** [comment]
Can you re-run “npm i” and send me the output?

**Comment by IanWalston** [comment]
not reproducible
